services:
  triptalk-db:
    image: mysql:8.0
    container_name: triptalk-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: khs08280
      MYSQL_DATABASE: triptalk
      MYSQL_USER: spring_server
      MYSQL_PASSWORD: khs08280
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  triptalk-app:
    build: .
    #    image: triptalk-registry.kr.ncr.ntruss.com/triptalk-app:latest
    container_name: triptalk-app
    ports:
      - "8080:8080"
    depends_on:
      - triptalk-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://triptalk-db:3306/triptalk?serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=spring_server
      - SPRING_DATASOURCE_PASSWORD=khs08280
      - SERVER_SSL_ENABLED=false
    restart: on-failure
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - triptalk-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:
